// Generated by CoffeeScript 2.5.1
export var Error = class Error {
  constructor() {}

  message() {
    return "Error";
  }

  toString() {
    return this.message();
  }

};

export var UnknownCommandError = class UnknownCommandError extends Error {
  constructor(token) {
    super();
    this.token = token;
  }

  message() {
    return `Unknown command ${this.token}`;
  }

};

export var StackUnderflowError = class StackUnderflowError extends Error {
  message() {
    return "Stack underflow";
  }

};

export var CallStackUnderflowError = class CallStackUnderflowError extends Error {
  message() {
    return "Call stack underflow";
  }

};

export var UnexpectedEOF = class UnexpectedEOF extends Error {
  message() {
    return "Unexpected EOF";
  }

};

export var UnexpectedParseError = class UnexpectedParseError extends Error {
  constructor(token) {
    super();
    this.token = token;
  }

  message() {
    return `Unexpected token ${this.token}`;
  }

};

export var CallNonFunction = class CallNonFunction extends Error {
  constructor(object) {
    super();
    this.object = object;
  }

  message() {
    return `Attempt to call non-function ${this.object}`;
  }

};

export var InvalidModifier = class InvalidModifier extends Error {
  constructor(token) {
    super();
    this.token = token;
  }

  message() {
    return `Invalid modifier(s) on ${this.token}`;
  }

};

export var IncompatibleArrayLengths = class IncompatibleArrayLengths extends Error {
  message() {
    return "Incompatible array lengths";
  }

};

export var InvalidInput = class InvalidInput extends Error {
  message() {
    return "Invalid input";
  }

};

export var TypeError = class TypeError extends Error {
  constructor(expected, value) {
    super();
    this.expected = expected;
    this.value = value;
  }

  message() {
    return `Type error (Expected ${this.expected} got ${this.value})`;
  }

};

export var StrEncodingError = class StrEncodingError extends Error {
  constructor(str) {
    super();
    this.str = str;
  }

  message() {
    return `String encoding error (${this.str})`;
  }

};

export var IncomparableValues = class IncomparableValues extends Error {
  constructor(lhs, rhs) {
    super();
    this.lhs = lhs;
    this.rhs = rhs;
  }

  message() {
    return `Attempt to compare ${this.lhs} and ${this.rhs}`;
  }

};

export var UserError = class UserError extends Error {
  constructor(value) {
    super();
    this.value = value;
  }

  message() {
    return `User error ${this.value}`;
  }

};

//# sourceMappingURL=error.js.map
