// Generated by CoffeeScript 2.5.1
import {
  DEFAULT_TRANSLATION_TABLE
} from './unicode_input.js';

export var printTable = function(node) {
  var flippedTable, k, result, v, v1;
  result = "";
  result += `<table class="input-table">
  <tr><th>Character</th><th>To Input</th></tr>`;
  flippedTable = {};
  for (k in DEFAULT_TRANSLATION_TABLE) {
    v = DEFAULT_TRANSLATION_TABLE[k];
    if (flippedTable[v] == null) {
      flippedTable[v] = [];
    }
    flippedTable[v].push(k);
  }
  for (k in flippedTable) {
    v = flippedTable[k];
    v1 = v.map(function(x) {
      return `<code>${x}</code>`;
    }).join(", ");
    result += `<tr>
  <td><code>${k}</code></td>
  <td>${v1}</td>
</tr>`;
  }
  result += `</table>`;
  return node.innerHTML = result;
};

//# sourceMappingURL=input_documentation.js.map
