// Generated by CoffeeScript 2.5.1
var DEBUG_MODE, inputManager;
import { tokenize, parse } from './parser.js';
import { Evaluator } from './eval.js';
import { Error } from './error.js';
import { FunctionLit } from './ast.js';
import { InputManager } from './unicode_input.js';
import Str from './str.js';
// Main entrypoint for the online interactive interpreter.
DEBUG_MODE = false;
inputManager = null;
export class InteractiveEvaluator extends Evaluator {
    constructor() {
        super();
        const inputField = document.querySelector("#input");
        if ((inputField == null) || (!(inputField instanceof HTMLTextAreaElement))) {
            throw "Could not find input field";
        }
        this.input = Str.fromString(inputField.value);
        this.inputPos = 0;
    }
    print(value) {
        const outputField = document.querySelector("#output");
        if ((outputField == null) || (!(outputField instanceof HTMLElement))) {
            throw "Could not find output field";
        }
        outputField.innerText += value.toString() + "\n";
    }
    readInput() {
        var result;
        if (this.inputPos >= this.input.length) {
            return void 0;
        }
        else {
            result = this.input.charAt(this.inputPos);
            this.inputPos += 1;
            return result;
        }
    }
    peekInput() {
        if (this.inputPos >= this.input.length) {
            return undefined;
        }
        else {
            return this.input.charAt(this.inputPos);
        }
    }
}
;
export var run = function () {
    var e, evaluator, parsed, text, tokens;
    const codeField = document.querySelector("#code");
    const outputField = document.querySelector("#output");
    const stackField = document.querySelector("#stack");
    if ((codeField == null) || (!(codeField instanceof HTMLTextAreaElement))) {
        throw "Could not find code field";
    }
    if ((outputField == null) || (!(outputField instanceof HTMLElement))) {
        throw "Could not find code field";
    }
    if ((stackField == null) || (!(stackField instanceof HTMLElement))) {
        throw "Could not find stack field";
    }
    text = codeField.value;
    evaluator = new InteractiveEvaluator();
    try {
        outputField.innerText = "";
        stackField.innerText = "";
        tokens = tokenize(text);
        parsed = parse(tokens);
        evaluator.pushCall(new FunctionLit(parsed));
        evaluator.eval(parsed);
        evaluator.popCall();
    }
    catch (error) {
        e = error;
        if (e instanceof Error && !DEBUG_MODE) {
            outputField.innerText += "\n\n" + e.toString() + "\n";
        }
        else {
            throw e;
        }
    }
    stackField.innerText = evaluator.stackToString();
};
export var initInputMgr = function () {
    inputManager = new InputManager();
    return inputManager.register(document.querySelector("#code"));
};
//# sourceMappingURL=main.js.map
