// Generated by CoffeeScript 2.5.1
var NUMS;

NUMS = "⓪①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳";

export var Modifier = class Modifier {};

export var NumModifier = class NumModifier extends Modifier {
  constructor(value) {
    super();
    this.value = value;
  }

  toString() {
    return NUMS.charAt(this.value);
  }

};

export var PrimeModifier = class PrimeModifier extends Modifier {
  toString() {
    return "′";
  }

};

export var toNumModifier = function(tok) {
  var result;
  if (tok.text.toString() === "") {
    return void 0;
  }
  result = NUMS.indexOf(tok.text.toString());
  if (result >= 0) {
    return new NumModifier(result);
  } else {
    return void 0;
  }
};

export var MAX_NUM_MODIFIER = 20;

//# sourceMappingURL=modifier.js.map
