// Generated by CoffeeScript 2.5.1
import { TypeError } from './error.js';
import { NumberLit, StringLit, ArrayLit } from './ast.js';
// Various typechecking functions. Unless otherwise stated, these each
// return their argument if successful and throw an Error.TypeError
// otherwise.
export var checkOrThrow = function (expecting, p) {
    return function (value) {
        if (p(value)) {
            return value;
        }
        else {
            throw new TypeError(expecting, value);
        }
    };
};
export var isNumber = checkOrThrow("number", function (v) {
    return v instanceof NumberLit;
});
export var isString = checkOrThrow("string", function (v) {
    return v instanceof StringLit;
});
export var isList = checkOrThrow("list", function (v) {
    return v instanceof ArrayLit;
});
export var isStringOrList = checkOrThrow("string or list", function (v) {
    return v instanceof StringLit || v instanceof ArrayLit;
});
//# sourceMappingURL=type_check.js.map
