// Generated by CoffeeScript 2.5.1
export var zip = function (a, b) {
    return a.map(function (v, i) {
        return [v, b[i]];
    });
};
export var arrayEq = function (a, b, fn = function (x, y) {
    return x === y;
}) {
    var ref, x, y, z;
    if (!(Array.isArray(a) && Array.isArray(b))) {
        return false;
    }
    if (a.length !== b.length) {
        return false;
    }
    ref = zip(a, b);
    for (z of ref) {
        [x, y] = z;
        if (!fn(x, y)) {
            return false;
        }
    }
    return true;
};
export var spliceStr = function (str, sub, a, b) {
    return str.substring(0, a) + sub + str.substring(b);
};
export var gcd = function (a, b) {
    while (b !== 0) {
        [a, b] = [b, (a % b + b) % b];
    }
    return a;
};
export var lcm = function (a, b) {
    var d;
    d = gcd(a, b);
    if (d === 0) {
        return 0;
    }
    else {
        return a * b / d;
    }
};
//# sourceMappingURL=util.js.map
